name: Merge Schedule

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    - cron: '15 * * * *'

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@b00191bec092ae480b63bf466fb94b5474b71cdd # v2.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
