---
name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt
          #      - name: Analysing the code with pylint
          #        run: |
          #          pylint $(git ls-files '*.py')
      - name: Convention Checking content/ dir
        run: |
           python tests/test_symlinks.py
      - name: Create symlinks and copy things to the right places
        run: |
          cd content
          python MAKESYMLINKS.py
          cd ..
      - name: Look for broken links in this branch # TODO: Use build.sh?
        run: |
          pip install -r tests/requirements.txt
          SITE_URL=http://127.0.0.1:8000 pelican content
          python tags_sorter.py
          SITE_URL=http://127.0.0.1:8000 pelican -l -r &
          sleep 5
          python tests/find_broken_links.py --host http://127.0.0.1:8000
      - name: Look for broken links deeper
        run: |
          pip install -r tests/requirements.txt
          SITE_URL=http://127.0.0.1:8000 pelican content
          python tags_sorter.py
          SITE_URL=http://127.0.0.1:8000 pelican -l -r &
          sleep 5
          python tests/find_broken_links_deeper.py --host http://127.0.0.1:8000
      - name: Look for broken links in production (a bit too late no?)
        run: |
          pip install -r tests/requirements.txt
          python tests/find_broken_links.py --host https://guldmyr.com
      - name: Look for metadata 
        run: |
          pip install -r tests/requirements.txt
          python tests/find_metadata.py
      - name: Hunt for CRLF encoded files
        run: |
          CRLF_FILES=$(find . -name '*.md' -exec file {} \;|grep -c CRLF || true)
          if [ $CRLF_FILES -gt 0 ]; then
            echo "Found CRLF files"
            exit 1
          fi
